import dns from "node:dns";
dns.setServers(["1.1.1.1","8.8.8.8"]);
import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sheard/Navbar";
import MarqueeText from "@/components/sheard/MarqueeText";
import Footer from "@/components/sheard/Footer";

const notoSerifBengali = Noto_Serif_Bengali({
  variable: "--font-noto-serif-bengali",
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Bangla News 24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-neutral-50">
        <Navbar />
        <MarqueeText />
        <main className="container mx-auto px-4">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
